### ISSUE TITLE
Change ADMINS

### ISSUE THREAD

**Issue by jdavid** [emencia/emencia_paste_djangocms_3#8]
Now ADMINS is set up so emails are sent to sys@dummy.com, this is a security problem.

Change so it looks like (for instance):

    ADMINS = [
    #    ('Admin', 'admin@example.com'),
    ]

(or change the command to generate new projects, so it asks for the value to put in this variable)

**Comment by sveetch** [comment]
Commented line has been done in last commit 5542adc4bd, will see further for the interactive option from commandline.

**Comment by sveetch** [comment]
I tried to see to add this as a question, but the paster way of interactive questions and how we use it, does not really fit to do this. I prefer to wait the "Epaster reboot" with cookiecutter to implement this sort of thing.

But if someone find a clean and cool way to implement it with paster, i won't opposite to.
