### ISSUE TITLE
Error deleting user on andmin interface.

### ISSUE THREAD

**Issue by slothyrulez** [emencia/emencia_paste_djangocms_3#9]
```
........
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_comments
```

Probably "django_comments" is missing on zinnia app requirements.

**Comment by sveetch** [comment]
Yep, have to add it to settings.INSTALLED_APP in the zinnia's mod, also maybe add a hint about to disable comments into docstring of the mod.
